[workspace]
resolver = "2"
members = [
    "helper/common",
    "helper/dbhelper",
    "helper/exception",
    "helper/macros/cfg_lib",
    "helper/macros/constructor",
    "gbserver",
]

[profile.dev]
debug = true
opt-level = 0
